name: 'CI workflow'

on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    # TODO: template for build to DRY for CI and for publish workflows
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout non PR
        uses: actions/checkout@v4.1.4
        # Do not trigger a checkout when opening PRs from a fork (helps avoid
        # "pwn request". See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target )
        if: github.event_name != 'pull_request_target'
        with:
          fetch-depth: '0'

      - name: Checkout PR
        uses: actions/checkout@v4.1.4
        if: github.event_name == 'pull_request_target'
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
          fetch-depth: '0'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --immutable

      - name: validate config
        run: yarn backstage-cli config:check --lax

      - name: lint
        run: yarn backstage-cli repo lint

      - name: type checking and declarations
        run: yarn tsc:full

      - name: build
        run: yarn backstage-cli repo build --all
        env:
          CI: true

      - name: verify type dependencies
        run: yarn lint:type-deps

      - name: test
        run: |
          yarn backstage-cli repo test --maxWorkers=3 --workerIdleMemoryLimit=1300M

      # Playwright e2e tests
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Run Playwright tests
        run: yarn test:e2e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload e2e tests result
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-test-report
          path: e2e-test-report/
          retention-days: 30
          include-hidden-files: true
